# Defines a default set of lint rules.
# For details and rationale, see https://dart.dev/lints.
#
# For a list of available lints, see
# https://dart-lang.github.io/linter/lints/options/options.html

include: package:lints/recommended.yaml

# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

# analyzer:
#   exclude:
#     - path/to/excluded/files/**
